<a href="https://colab.research.google.com/github/NikhilGeorge01/DeepLearningPractice/blob/main/BooleanLogics(Week2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

class Perceptron:
    def __init__(self, n, lr=0.1):
        self.w, self.b, self.lr = np.random.randn(n), np.random.randn(), lr

    def predict(self, X):
        return (np.dot(X, self.w) + self.b >= 0).astype(int)

    def fit(self, X, y, epochs=100):
        for _ in range(epochs):
            for xi, yi in zip(X, y):
                err = yi - (np.dot(xi, self.w) + self.b >= 0)
                self.w += self.lr * err * xi
                self.b += self.lr * err

In [33]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
aY = np.array([0,0,0,1])
oY = np.array([0,1,1,1])

aMod = Perceptron(n = 2)
oMod = Perceptron(n = 2)
aMod.fit(X,aY)
oMod.fit(X, oY)
print(aMod.predict(X), oMod.predict(X))

[0 0 0 1] [0 1 1 1]


In [4]:
xrY = np.array([0,1,1,0])
xrMod = Perceptron(n=2)
xrMod.fit(X, xrY, epochs=100)
print(xrMod.predict(X))

[1 1 0 0]


In [6]:
from tensorflow import keras
from tensorflow.keras import layers

In [12]:
model = keras.Sequential([
    layers.Dense(4, activation='relu', input_shape=(2,)),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.fit(X, xrY, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0981
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.0980
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0978
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0977
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0976
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.0974
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.0973
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.0971
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.0970
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.0969


In [17]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.14157814]
 [0.9243657 ]
 [0.9253938 ]
 [0.07514462]]


In [18]:
import numpy as np

def step(z):
    return 1 if z >= 0 else 0

values = [-0.0001, 0.0001]

for v in values:
    print(v, "->", step(v))

-0.0001 -> 0
0.0001 -> 1


In [19]:
class MPNeuron:
    def __init__(self, threshold=2):
        self.threshold = threshold

    def predict(self, X):
        return (np.sum(X, axis=1) >= self.threshold).astype(int)

In [26]:
class PerceptronNoB:
    def __init__(self, n, lr=0.1):
        self.w, self.lr = np.random.randn(n), lr

    def predict(self, X):
        return (np.dot(X, self.w) >= 0).astype(int)

    def fit(self, X, y, epochs=100):
        for _ in range(epochs):
            for xi, yi in zip(X, y):
                err = yi - (np.dot(xi, self.w) >= 0)
                self.w += self.lr * err * xi

In [22]:
X = np.array([
    [1, 1, 1, 0.9],  # Nolan + Damon + Thriller + High rating
    [0, 1, 1, 0.8],
    [1, 0, 0, 0.6],
    [0, 0, 0, 0.4],
    [1, 1, 0, 0.7],
    [0, 1, 0, 0.5]
])
y = np.array([1,1,1,0,1,0])

In [27]:
m1 = MPNeuron()
m2 = PerceptronNoB(n=4)
m3 = Perceptron(n=4)

m2.fit(X,y)
m3.fit(X,y)

print(m1.predict(X))
print(m2.predict(X))
print(m3.predict(X))

[1 1 0 0 1 0]
[1 1 1 0 1 0]
[1 1 1 0 1 0]


In [49]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y_arr= np.array([
    [0,0,0,0],
    [0,0,0,1],
    [0,0,1,0],
    [0,0,1,1],
    [0,1,0,0],
    [0,1,0,1],
    [0,1,1,0],
    [0,1,1,1],
    [1,0,0,0],
    [1,0,0,1],
    [1,0,1,0],
    [1,0,1,1],
    [1,1,0,0],
    [1,1,0,1],
    [1,1,1,0],
    [1,1,1,1]
])
print(len(y_arr))

16


In [48]:
correct = 0
for y in y_arr:
  m = Perceptron(n = 2)
  y = np.array(y)
  m.fit(X,y)
  pred = m.predict(X)
  if list(pred) == list(y):
    correct += 1
  print(pred)
print(correct)




[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[1 1 0 0]
[0 1 1 1]
[1 0 0 0]
[0 0 1 0]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]
14


In [50]:
import numpy as np

def step(x):
    return (x >= 0).astype(int)

class BooleanMLP:
    def __init__(self, output_truth):
        # output_truth = [y00, y01, y10, y11]
        self.output_truth = output_truth

    def forward(self, X):
        x1, x2 = X[:,0], X[:,1]

        h1 = step(-x1 - x2 + 1.5)
        h2 = step(-x1 + x2 - 0.5)
        h3 = step(x1 - x2 - 0.5)
        h4 = step(x1 + x2 - 1.5)

        H = np.stack([h1,h2,h3,h4], axis=1)

        # Output weights chosen from truth table
        w = np.array(self.output_truth)

        y = step(np.dot(H, w) - 0.5)
        return y